### ISSUE TITLE
"Fire" control not working

### ISSUE THREAD

**Issue by RogueIMP** [nmilford/stormLauncher#5]
Everything works, except the "Fire" control.  When troubleshooting, the errors appear to be coming from the line:  
self.dev.ctrl_transfer(0x21,0x09,0,0,[0x02,0x10,0x00,0x00,0x00,0x00,0x00,0x00])
It appears that the machine code is wrong/off, and I don't know how to find out the correct one.
I've tested different codes, changing the 0x10 to 0x01 - 0x12, with no success.
Any advice???

**Comment by mmadiraju** [comment]
Same issue here with "Fire". Traceback is below. Please advice.

Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1535, in **call**
    return self.func(*args)
  File "./stormLauncher.py", line 118, in turretFire
    self.dev.ctrl_transfer(0x21,0x09,0,0,[0x02,0x10,0x00,0x00,0x00,0x00,0x00,0x00],0)
  File "/usr/local/lib/python2.7/dist-packages/usb/core.py", line 971, in ctrl_transfer
    self.__get_timeout(timeout))
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 819, in ctrl_transfer
    timeout))
  File "/usr/local/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 552, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
USBError: [Errno 5] Input/Output Error
